// Copyright 2017 Sourcerer, Inc. All Rights Reserved.
// Author: Anatoly Kislov (anatoly@sourcerer.io)
// Author: Liubov Yaronskaya (lyaronskaya@sourcerer.io)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.5
// source: sourcerer.proto

// Java compiler settings.

package app

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Commit.
type Commit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Re-hash of hash of a commit.
	Rehash string `protobuf:"bytes,1,opt,name=rehash,proto3" json:"rehash,omitempty"`
	// Hash of repo.
	RepoRehash string `protobuf:"bytes,2,opt,name=repo_rehash,json=repoRehash,proto3" json:"repo_rehash,omitempty"`
	// Re-hash of hash of tree object of a commit.
	TreeRehash string `protobuf:"bytes,3,opt,name=tree_rehash,json=treeRehash,proto3" json:"tree_rehash,omitempty"`
	// Information about author of a commit.
	AuthorName  string `protobuf:"bytes,4,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorEmail string `protobuf:"bytes,5,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	// Timestamp of a commit creation in seconds UTC+0.
	Date uint64 `protobuf:"varint,6,opt,name=date,proto3" json:"date,omitempty"`
	// Is quality commit.
	IsQommit bool `protobuf:"varint,7,opt,name=is_qommit,json=isQommit,proto3" json:"is_qommit,omitempty"`
	// Number of lines for a whole commit.
	NumLinesAdded   int32 `protobuf:"varint,8,opt,name=num_lines_added,json=numLinesAdded,proto3" json:"num_lines_added,omitempty"`
	NumLinesDeleted int32 `protobuf:"varint,9,opt,name=num_lines_deleted,json=numLinesDeleted,proto3" json:"num_lines_deleted,omitempty"`
	// Tech stats on a commit.
	Stats         []*CommitStats `protobuf:"bytes,10,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_sourcerer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{0}
}

func (x *Commit) GetRehash() string {
	if x != nil {
		return x.Rehash
	}
	return ""
}

func (x *Commit) GetRepoRehash() string {
	if x != nil {
		return x.RepoRehash
	}
	return ""
}

func (x *Commit) GetTreeRehash() string {
	if x != nil {
		return x.TreeRehash
	}
	return ""
}

func (x *Commit) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *Commit) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *Commit) GetDate() uint64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Commit) GetIsQommit() bool {
	if x != nil {
		return x.IsQommit
	}
	return false
}

func (x *Commit) GetNumLinesAdded() int32 {
	if x != nil {
		return x.NumLinesAdded
	}
	return 0
}

func (x *Commit) GetNumLinesDeleted() int32 {
	if x != nil {
		return x.NumLinesDeleted
	}
	return 0
}

func (x *Commit) GetStats() []*CommitStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// Tech stats on a commit.
type CommitStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of lines for a specific technology.
	NumLinesAdded   int32 `protobuf:"varint,1,opt,name=num_lines_added,json=numLinesAdded,proto3" json:"num_lines_added,omitempty"`
	NumLinesDeleted int32 `protobuf:"varint,2,opt,name=num_lines_deleted,json=numLinesDeleted,proto3" json:"num_lines_deleted,omitempty"`
	// Technology type (language/framework/library).
	Type int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	// Technology name.
	Tech          string `protobuf:"bytes,4,opt,name=tech,proto3" json:"tech,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitStats) Reset() {
	*x = CommitStats{}
	mi := &file_sourcerer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitStats) ProtoMessage() {}

func (x *CommitStats) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitStats.ProtoReflect.Descriptor instead.
func (*CommitStats) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{1}
}

func (x *CommitStats) GetNumLinesAdded() int32 {
	if x != nil {
		return x.NumLinesAdded
	}
	return 0
}

func (x *CommitStats) GetNumLinesDeleted() int32 {
	if x != nil {
		return x.NumLinesDeleted
	}
	return 0
}

func (x *CommitStats) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CommitStats) GetTech() string {
	if x != nil {
		return x.Tech
	}
	return ""
}

// Used to send multiple commits in one request.
type CommitGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*Commit              `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitGroup) Reset() {
	*x = CommitGroup{}
	mi := &file_sourcerer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitGroup) ProtoMessage() {}

func (x *CommitGroup) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitGroup.ProtoReflect.Descriptor instead.
func (*CommitGroup) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{2}
}

func (x *CommitGroup) GetCommits() []*Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

// Key-value statistics for fun facts.
type Fact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Key           int32                  `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	Value1        string                 `protobuf:"bytes,3,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2        string                 `protobuf:"bytes,4,opt,name=value2,proto3" json:"value2,omitempty"`
	Value3        string                 `protobuf:"bytes,5,opt,name=value3,proto3" json:"value3,omitempty"`
	Value4        string                 `protobuf:"bytes,6,opt,name=value4,proto3" json:"value4,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	RepoRehash    string                 `protobuf:"bytes,8,opt,name=repo_rehash,json=repoRehash,proto3" json:"repo_rehash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fact) Reset() {
	*x = Fact{}
	mi := &file_sourcerer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{3}
}

func (x *Fact) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Fact) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Fact) GetValue1() string {
	if x != nil {
		return x.Value1
	}
	return ""
}

func (x *Fact) GetValue2() string {
	if x != nil {
		return x.Value2
	}
	return ""
}

func (x *Fact) GetValue3() string {
	if x != nil {
		return x.Value3
	}
	return ""
}

func (x *Fact) GetValue4() string {
	if x != nil {
		return x.Value4
	}
	return ""
}

func (x *Fact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Fact) GetRepoRehash() string {
	if x != nil {
		return x.RepoRehash
	}
	return ""
}

// Used to send multiple stats in one request.
type FactGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facts         []*Fact                `protobuf:"bytes,1,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactGroup) Reset() {
	*x = FactGroup{}
	mi := &file_sourcerer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactGroup) ProtoMessage() {}

func (x *FactGroup) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactGroup.ProtoReflect.Descriptor instead.
func (*FactGroup) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{4}
}

func (x *FactGroup) GetFacts() []*Fact {
	if x != nil {
		return x.Facts
	}
	return nil
}

// Used to authors for invitational procedures.
type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RepoRehash    string                 `protobuf:"bytes,2,opt,name=repo_rehash,json=repoRehash,proto3" json:"repo_rehash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_sourcerer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{5}
}

func (x *Author) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetRepoRehash() string {
	if x != nil {
		return x.RepoRehash
	}
	return ""
}

type AuthorGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       []*Author              `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorGroup) Reset() {
	*x = AuthorGroup{}
	mi := &file_sourcerer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorGroup) ProtoMessage() {}

func (x *AuthorGroup) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorGroup.ProtoReflect.Descriptor instead.
func (*AuthorGroup) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{6}
}

func (x *AuthorGroup) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

// User properties and indentity information about repos.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of known repos containing basic information for indentifying repo.
	Repos []*Repo `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	// List of known emails.
	Emails        []*UserEmail `protobuf:"bytes,2,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_sourcerer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetRepos() []*Repo {
	if x != nil {
		return x.Repos
	}
	return nil
}

func (x *User) GetEmails() []*UserEmail {
	if x != nil {
		return x.Emails
	}
	return nil
}

// Email of user with its status information.
type UserEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Primary       bool                   `protobuf:"varint,2,opt,name=primary,proto3" json:"primary,omitempty"`
	Verified      bool                   `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEmail) Reset() {
	*x = UserEmail{}
	mi := &file_sourcerer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEmail) ProtoMessage() {}

func (x *UserEmail) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEmail.ProtoReflect.Descriptor instead.
func (*UserEmail) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{8}
}

func (x *UserEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserEmail) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

func (x *UserEmail) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

// Repository parameters for hashing.
type Repo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Repository rehash according to initial commit rehash, remote and user
	// handle if no remote presented.
	Rehash string `protobuf:"bytes,1,opt,name=rehash,proto3" json:"rehash,omitempty"`
	// Rehash of first commit in repo. Used for indentifying forks.
	InitialCommitRehash string `protobuf:"bytes,2,opt,name=initial_commit_rehash,json=initialCommitRehash,proto3" json:"initial_commit_rehash,omitempty"`
	// Authors' email filter for hashed commits. If empty list then hash only
	// commits that created by current user.
	Emails []string `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	// Raw commits server history. Used to find overlap of commits. Hashing
	// starts after last commit from the overlap.
	Commits []*Commit `protobuf:"bytes,5,rep,name=commits,proto3" json:"commits,omitempty"`
	// Meta info about repo. Is not used for a locally run app.
	Meta *RepoMeta `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	// Processing session id, used to check the processing status.
	ProcessEntryId uint32 `protobuf:"varint,7,opt,name=process_entry_id,json=processEntryId,proto3" json:"process_entry_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Repo) Reset() {
	*x = Repo{}
	mi := &file_sourcerer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repo) ProtoMessage() {}

func (x *Repo) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repo.ProtoReflect.Descriptor instead.
func (*Repo) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{9}
}

func (x *Repo) GetRehash() string {
	if x != nil {
		return x.Rehash
	}
	return ""
}

func (x *Repo) GetInitialCommitRehash() string {
	if x != nil {
		return x.InitialCommitRehash
	}
	return ""
}

func (x *Repo) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *Repo) GetCommits() []*Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *Repo) GetMeta() *RepoMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Repo) GetProcessEntryId() uint32 {
	if x != nil {
		return x.ProcessEntryId
	}
	return 0
}

// Meta info about repo. Is not used for a locally run app.
type RepoMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HosterId      string                 `protobuf:"bytes,1,opt,name=hosterId,proto3" json:"hosterId,omitempty"`
	Service       string                 `protobuf:"bytes,6,opt,name=service,proto3" json:"service,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerName     string                 `protobuf:"bytes,3,opt,name=ownerName,proto3" json:"ownerName,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	HtmlUrl       string                 `protobuf:"bytes,4,opt,name=htmlUrl,proto3" json:"htmlUrl,omitempty"`
	CloneUrl      string                 `protobuf:"bytes,5,opt,name=cloneUrl,proto3" json:"cloneUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoMeta) Reset() {
	*x = RepoMeta{}
	mi := &file_sourcerer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoMeta) ProtoMessage() {}

func (x *RepoMeta) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoMeta.ProtoReflect.Descriptor instead.
func (*RepoMeta) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{10}
}

func (x *RepoMeta) GetHosterId() string {
	if x != nil {
		return x.HosterId
	}
	return ""
}

func (x *RepoMeta) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RepoMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RepoMeta) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *RepoMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RepoMeta) GetHtmlUrl() string {
	if x != nil {
		return x.HtmlUrl
	}
	return ""
}

func (x *RepoMeta) GetCloneUrl() string {
	if x != nil {
		return x.CloneUrl
	}
	return ""
}

// Errors from server.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_sourcerer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{11}
}

func (x *Error) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Errors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*Error               `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Errors) Reset() {
	*x = Errors{}
	mi := &file_sourcerer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Errors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Errors) ProtoMessage() {}

func (x *Errors) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Errors.ProtoReflect.Descriptor instead.
func (*Errors) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{12}
}

func (x *Errors) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Status of processing.
type Process struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Entries           []*ProcessEntry        `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	RequestNumEntries uint32                 `protobuf:"varint,5,opt,name=request_num_entries,json=requestNumEntries,proto3" json:"request_num_entries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_sourcerer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{13}
}

func (x *Process) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Process) GetEntries() []*ProcessEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Process) GetRequestNumEntries() uint32 {
	if x != nil {
		return x.RequestNumEntries
	}
	return 0
}

type ProcessEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode     uint32                 `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEntry) Reset() {
	*x = ProcessEntry{}
	mi := &file_sourcerer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEntry) ProtoMessage() {}

func (x *ProcessEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEntry.ProtoReflect.Descriptor instead.
func (*ProcessEntry) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessEntry) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProcessEntry) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProcessEntry) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type AuthorDistance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	RepoRehash    string                 `protobuf:"bytes,3,opt,name=repo_rehash,json=repoRehash,proto3" json:"repo_rehash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorDistance) Reset() {
	*x = AuthorDistance{}
	mi := &file_sourcerer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorDistance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorDistance) ProtoMessage() {}

func (x *AuthorDistance) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorDistance.ProtoReflect.Descriptor instead.
func (*AuthorDistance) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{15}
}

func (x *AuthorDistance) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthorDistance) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AuthorDistance) GetRepoRehash() string {
	if x != nil {
		return x.RepoRehash
	}
	return ""
}

type AuthorDistanceGroup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthorDistances []*AuthorDistance      `protobuf:"bytes,1,rep,name=author_distances,json=authorDistances,proto3" json:"author_distances,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorDistanceGroup) Reset() {
	*x = AuthorDistanceGroup{}
	mi := &file_sourcerer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorDistanceGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorDistanceGroup) ProtoMessage() {}

func (x *AuthorDistanceGroup) ProtoReflect() protoreflect.Message {
	mi := &file_sourcerer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorDistanceGroup.ProtoReflect.Descriptor instead.
func (*AuthorDistanceGroup) Descriptor() ([]byte, []int) {
	return file_sourcerer_proto_rawDescGZIP(), []int{16}
}

func (x *AuthorDistanceGroup) GetAuthorDistances() []*AuthorDistance {
	if x != nil {
		return x.AuthorDistances
	}
	return nil
}

var File_sourcerer_proto protoreflect.FileDescriptor

const file_sourcerer_proto_rawDesc = "" +
	"\n" +
	"\x0fsourcerer.proto\x12\x03app\"\xd3\x02\n" +
	"\x06Commit\x12\x16\n" +
	"\x06rehash\x18\x01 \x01(\tR\x06rehash\x12\x1f\n" +
	"\vrepo_rehash\x18\x02 \x01(\tR\n" +
	"repoRehash\x12\x1f\n" +
	"\vtree_rehash\x18\x03 \x01(\tR\n" +
	"treeRehash\x12\x1f\n" +
	"\vauthor_name\x18\x04 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fauthor_email\x18\x05 \x01(\tR\vauthorEmail\x12\x12\n" +
	"\x04date\x18\x06 \x01(\x04R\x04date\x12\x1b\n" +
	"\tis_qommit\x18\a \x01(\bR\bisQommit\x12&\n" +
	"\x0fnum_lines_added\x18\b \x01(\x05R\rnumLinesAdded\x12*\n" +
	"\x11num_lines_deleted\x18\t \x01(\x05R\x0fnumLinesDeleted\x12&\n" +
	"\x05stats\x18\n" +
	" \x03(\v2\x10.app.CommitStatsR\x05stats\"\x89\x01\n" +
	"\vCommitStats\x12&\n" +
	"\x0fnum_lines_added\x18\x01 \x01(\x05R\rnumLinesAdded\x12*\n" +
	"\x11num_lines_deleted\x18\x02 \x01(\x05R\x0fnumLinesDeleted\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x12\n" +
	"\x04tech\x18\x04 \x01(\tR\x04tech\"4\n" +
	"\vCommitGroup\x12%\n" +
	"\acommits\x18\x01 \x03(\v2\v.app.CommitR\acommits\"\xc3\x01\n" +
	"\x04Fact\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03key\x18\x02 \x01(\x05R\x03key\x12\x16\n" +
	"\x06value1\x18\x03 \x01(\tR\x06value1\x12\x16\n" +
	"\x06value2\x18\x04 \x01(\tR\x06value2\x12\x16\n" +
	"\x06value3\x18\x05 \x01(\tR\x06value3\x12\x16\n" +
	"\x06value4\x18\x06 \x01(\tR\x06value4\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x1f\n" +
	"\vrepo_rehash\x18\b \x01(\tR\n" +
	"repoRehash\",\n" +
	"\tFactGroup\x12\x1f\n" +
	"\x05facts\x18\x01 \x03(\v2\t.app.FactR\x05facts\"S\n" +
	"\x06Author\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vrepo_rehash\x18\x02 \x01(\tR\n" +
	"repoRehash\"4\n" +
	"\vAuthorGroup\x12%\n" +
	"\aauthors\x18\x01 \x03(\v2\v.app.AuthorR\aauthors\"O\n" +
	"\x04User\x12\x1f\n" +
	"\x05repos\x18\x01 \x03(\v2\t.app.RepoR\x05repos\x12&\n" +
	"\x06emails\x18\x02 \x03(\v2\x0e.app.UserEmailR\x06emails\"W\n" +
	"\tUserEmail\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\aprimary\x18\x02 \x01(\bR\aprimary\x12\x1a\n" +
	"\bverified\x18\x03 \x01(\bR\bverified\"\xde\x01\n" +
	"\x04Repo\x12\x16\n" +
	"\x06rehash\x18\x01 \x01(\tR\x06rehash\x122\n" +
	"\x15initial_commit_rehash\x18\x02 \x01(\tR\x13initialCommitRehash\x12\x16\n" +
	"\x06emails\x18\x04 \x03(\tR\x06emails\x12%\n" +
	"\acommits\x18\x05 \x03(\v2\v.app.CommitR\acommits\x12!\n" +
	"\x04meta\x18\x06 \x01(\v2\r.app.RepoMetaR\x04meta\x12(\n" +
	"\x10process_entry_id\x18\a \x01(\rR\x0eprocessEntryId\"\xca\x01\n" +
	"\bRepoMeta\x12\x1a\n" +
	"\bhosterId\x18\x01 \x01(\tR\bhosterId\x12\x18\n" +
	"\aservice\x18\x06 \x01(\tR\aservice\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\townerName\x18\x03 \x01(\tR\townerName\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x18\n" +
	"\ahtmlUrl\x18\x04 \x01(\tR\ahtmlUrl\x12\x1a\n" +
	"\bcloneUrl\x18\x05 \x01(\tR\bcloneUrl\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x06Errors\x12\"\n" +
	"\x06errors\x18\x01 \x03(\v2\n" +
	".app.ErrorR\x06errors\"v\n" +
	"\aProcess\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12+\n" +
	"\aentries\x18\x04 \x03(\v2\x11.app.ProcessEntryR\aentries\x12.\n" +
	"\x13request_num_entries\x18\x05 \x01(\rR\x11requestNumEntries\"U\n" +
	"\fProcessEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\rR\terrorCode\"]\n" +
	"\x0eAuthorDistance\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x1f\n" +
	"\vrepo_rehash\x18\x03 \x01(\tR\n" +
	"repoRehash\"U\n" +
	"\x13AuthorDistanceGroup\x12>\n" +
	"\x10author_distances\x18\x01 \x03(\v2\x13.app.AuthorDistanceR\x0fauthorDistancesB\r\n" +
	"\x03appB\x06Protosb\x06proto3"

var (
	file_sourcerer_proto_rawDescOnce sync.Once
	file_sourcerer_proto_rawDescData []byte
)

func file_sourcerer_proto_rawDescGZIP() []byte {
	file_sourcerer_proto_rawDescOnce.Do(func() {
		file_sourcerer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sourcerer_proto_rawDesc), len(file_sourcerer_proto_rawDesc)))
	})
	return file_sourcerer_proto_rawDescData
}

var file_sourcerer_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_sourcerer_proto_goTypes = []any{
	(*Commit)(nil),              // 0: app.Commit
	(*CommitStats)(nil),         // 1: app.CommitStats
	(*CommitGroup)(nil),         // 2: app.CommitGroup
	(*Fact)(nil),                // 3: app.Fact
	(*FactGroup)(nil),           // 4: app.FactGroup
	(*Author)(nil),              // 5: app.Author
	(*AuthorGroup)(nil),         // 6: app.AuthorGroup
	(*User)(nil),                // 7: app.User
	(*UserEmail)(nil),           // 8: app.UserEmail
	(*Repo)(nil),                // 9: app.Repo
	(*RepoMeta)(nil),            // 10: app.RepoMeta
	(*Error)(nil),               // 11: app.Error
	(*Errors)(nil),              // 12: app.Errors
	(*Process)(nil),             // 13: app.Process
	(*ProcessEntry)(nil),        // 14: app.ProcessEntry
	(*AuthorDistance)(nil),      // 15: app.AuthorDistance
	(*AuthorDistanceGroup)(nil), // 16: app.AuthorDistanceGroup
}
var file_sourcerer_proto_depIdxs = []int32{
	1,  // 0: app.Commit.stats:type_name -> app.CommitStats
	0,  // 1: app.CommitGroup.commits:type_name -> app.Commit
	3,  // 2: app.FactGroup.facts:type_name -> app.Fact
	5,  // 3: app.AuthorGroup.authors:type_name -> app.Author
	9,  // 4: app.User.repos:type_name -> app.Repo
	8,  // 5: app.User.emails:type_name -> app.UserEmail
	0,  // 6: app.Repo.commits:type_name -> app.Commit
	10, // 7: app.Repo.meta:type_name -> app.RepoMeta
	11, // 8: app.Errors.errors:type_name -> app.Error
	14, // 9: app.Process.entries:type_name -> app.ProcessEntry
	15, // 10: app.AuthorDistanceGroup.author_distances:type_name -> app.AuthorDistance
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sourcerer_proto_init() }
func file_sourcerer_proto_init() {
	if File_sourcerer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sourcerer_proto_rawDesc), len(file_sourcerer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sourcerer_proto_goTypes,
		DependencyIndexes: file_sourcerer_proto_depIdxs,
		MessageInfos:      file_sourcerer_proto_msgTypes,
	}.Build()
	File_sourcerer_proto = out.File
	file_sourcerer_proto_goTypes = nil
	file_sourcerer_proto_depIdxs = nil
}
